//! §4.4 **frame-erasure concealment** — the decoder-side error-recovery
//! machinery that reconstructs a frame whose 80-bit payload was lost.
//!
//! Clause 4.4 (06/2012 Recommendation): "An error concealment procedure
//! has been incorporated in the decoder to reduce the degradation in the
//! reconstructed speech because of frame erasures in the bitstream. …
//! The method replaces the missing excitation signal with one of similar
//! characteristics, while gradually decaying its energy." The mechanism
//! that *detects* an erasure is explicitly out of scope ("not defined in
//! this Recommendation, and will depend on the application"); this module
//! supplies the four reconstruction steps the spec *does* define, driven
//! by an externally-supplied erasure flag.
//!
//! ## Spec source — clause 4.4, equations (93)–(96) (06/2012 Rec.)
//!
//! The clause lists four steps for an erased frame:
//!
//! 1. **§4.4.1 repetition of synthesis-filter parameters** — "The
//!    synthesis filter in an erased frame uses the LP parameters of the
//!    last good frame." (The LP-parameter repeat itself is a decode-chain
//!    concern; this module owns the *classification* and *excitation*
//!    steps, exposing the repeat decision via [`Concealer::is_erased`].)
//! 2. **§4.4.2 attenuation of adaptive and fixed-codebook gains** —
//!    eq (93) and eq (94) below.
//! 3. **§4.4.3 attenuation of the gain-predictor memory** — eq (95).
//! 4. **§4.4.4 generation of the replacement excitation** — periodic vs
//!    non-periodic, governed by the §4.4 voicing class and eq (96).
//!
//! ### Voicing classification (§4.4)
//!
//! Clause 4.4: "a voicing classifier based on the long-term prediction
//! gain, which is computed as part of the long-term postfilter analysis.
//! The long-term postfilter (see clause 4.2.1) finds the long-term
//! predictor for which the prediction gain is more than 3 dB. This is
//! done by setting a threshold of 0.5 on the squared normalized
//! correlation of equation (82). For the error concealment process, a
//! 10 ms frame is declared **periodic** if at least one 5 ms subframe
//! has a long-term prediction gain of more than 3 dB. Otherwise the
//! frame is declared **non-periodic**. An erased frame inherits its
//! class from the preceding (reconstructed) speech frame."
//!
//! The "long-term prediction gain of more than 3 dB" test is exactly the
//! eq (82) enable decision the §4.2.1
//! [`crate::long_term_postfilter::LongTermPostfilter`] already makes: the
//! filter is enabled (non-zero `g_l`) precisely when the squared
//! normalised correlation clears the `0.5` threshold. So a subframe is
//! "voiced" iff its [`crate::long_term_postfilter::LongTermDecision`] has
//! `gain > 0`, and the frame is periodic iff *any* of its two subframes
//! is voiced.
//!
//! ### eq (93) — fixed-codebook gain attenuation (§4.4.2)
//!
//! ```text
//! ĝ_c^(m) = 0.98 · ĝ_c^(m−1)
//! ```
//!
//! where `m` is the subframe index — the fixed-codebook gain of the
//! erased subframe is `0.98` of the previous subframe's gain.
//!
//! ### eq (94) — adaptive-codebook gain attenuation (§4.4.2)
//!
//! ```text
//! ĝ_p^(m) = 0.9 · ĝ_p^(m−1)        bounded ĝ_p^(m) < 0.9
//! ```
//!
//! the adaptive (pitch) gain of the erased subframe is `0.9` of the
//! previous gain, additionally capped just below `0.9` so a chain of
//! erasures cannot let the pitch gain sit at or above `0.9`.
//!
//! ### eq (95) — gain-predictor-memory attenuation (§4.4.3)
//!
//! ```text
//! Û^(m) = ( 0.25 · Σ_{i=1}^{4} Û^(m−i) ) − 4.0      bounded Û^(m) ≥ −14
//! ```
//!
//! clause 4.4.3: "the memory of the gain predictor is updated with an
//! attenuated version of the codebook energy. The value of `Û(m)` … is
//! set to the averaged quantized gain prediction-error, attenuated by
//! 4 dB" — the average of the four
//! [`crate::gain_predict::GainPredictor`] history slots, minus 4 dB,
//! floored at the `−14` spec start-up value.
//!
//! ### eq (96) — replacement-excitation random generator (§4.4.4)
//!
//! ```text
//! seed = 31821 · seed + 13849          (16-bit wrap, initial seed 21845)
//! ```
//!
//! clause 4.4.4 (non-periodic case): "The fixed-codebook contribution is
//! generated by randomly selecting a codebook index and sign index. The
//! random generator is based on [eq (96)] with the initial seed value of
//! 21845. The fixed-codebook index is derived from the 13 least
//! significant bits of the next random number. The fixed-codebook sign is
//! derived from the 4 least significant bits of the next random number."
//!
//! ### Replacement excitation (§4.4.4)
//!
//! The excitation follows the voicing class of the last reconstructed
//! frame:
//!
//! - **periodic** — "only the adaptive codebook is used, and the
//!   fixed-codebook contribution is set to zero. The pitch delay is based
//!   on the integer part of the pitch delay in the previous frame, and is
//!   repeated for each successive frame. To avoid excessive periodicity
//!   the delay is increased by one for each next subframe but bounded by
//!   143. The adaptive-codebook gain is … attenuated value according to
//!   equation (94)." → [`Concealer::periodic_pitch_delay`].
//! - **non-periodic** — "the adaptive-codebook contribution is set to
//!   zero. The fixed-codebook contribution is generated by randomly
//!   selecting a codebook index and sign index … The fixed-codebook gain
//!   is attenuated according to equation (93)." →
//!   [`Concealer::next_random_excitation`].
//!
//! ## State
//!
//! [`Concealer`] owns the running voicing class (updated every *good*
//! frame, inherited across erasures), the eq (96) random seed (spec
//! start-up `21845`), and the integer pitch delay carried for the
//! periodic-case eq-94 repeat. The §4.4.2/§4.4.3 attenuations are pure
//! functions of the caller-held gains / predictor (the decode chain owns
//! the actual `ĝ_p`, `ĝ_c`, and [`crate::gain_predict::GainPredictor`]),
//! so they are exposed as associated functions rather than mutating
//! private state.

use crate::gain_predict::{GainPredictor, GAIN_PREDICTOR_INIT_DB};
use crate::long_term_postfilter::LongTermDecision;
use crate::tables::MA_NP;

/// eq (93) fixed-codebook-gain attenuation factor (§4.4.2): `0.98`.
pub const FIXED_GAIN_ATTENUATION: f32 = 0.98;

/// eq (94) adaptive-codebook-gain attenuation factor (§4.4.2): `0.9`.
pub const ADAPTIVE_GAIN_ATTENUATION: f32 = 0.9;

/// eq (94) upper bound on the attenuated adaptive gain (§4.4.2):
/// `ĝ_p^(m) < 0.9`. The attenuated value is capped strictly below this
/// so a run of erasures cannot pin the pitch gain at the bound.
pub const ADAPTIVE_GAIN_CAP: f32 = 0.9;

/// Returns one ULP below [`ADAPTIVE_GAIN_CAP`] — the largest `f32`
/// strictly less than `0.9`, realising the eq (94) strict `< 0.9` bound
/// on an MSRV that predates `f32::next_down`. `0.9_f32` has a positive
/// sign and non-zero mantissa, so decrementing the raw bit pattern by one
/// steps down to the immediately smaller representable value.
#[must_use]
fn adaptive_gain_cap_below() -> f32 {
    f32::from_bits(ADAPTIVE_GAIN_CAP.to_bits() - 1)
}

/// eq (95) averaging weight on the four gain-predictor history slots
/// (§4.4.3): `0.25` (the arithmetic mean of the four `Û^(m−i)`).
pub const PREDICTOR_MEMORY_AVERAGE_WEIGHT: f32 = 0.25;

/// eq (95) constant 4 dB attenuation subtracted from the averaged
/// predictor memory (§4.4.3).
pub const PREDICTOR_MEMORY_ATTENUATION_DB: f32 = 4.0;

/// eq (95) lower bound on the attenuated predictor memory (§4.4.3):
/// `Û^(m) ≥ −14`. This is the same `−14` dB the predictor history
/// starts at (spec Table 9 / clause 4.3,
/// [`GAIN_PREDICTOR_INIT_DB`]).
pub const PREDICTOR_MEMORY_FLOOR_DB: f32 = GAIN_PREDICTOR_INIT_DB;

/// eq (96) random-generator multiplier (§4.4.4).
pub const RANDOM_MULTIPLIER: u16 = 31821;

/// eq (96) random-generator increment (§4.4.4).
pub const RANDOM_INCREMENT: u16 = 13849;

/// §4.4.4 initial random-generator seed: `21845`.
pub const RANDOM_SEED_INIT: u16 = 21845;

/// §4.4.4 number of least-significant bits of the random number used as
/// the replacement fixed-codebook **index** (13).
pub const RANDOM_INDEX_BITS: u32 = 13;

/// §4.4.4 number of least-significant bits of the random number used as
/// the replacement fixed-codebook **sign** field (4).
pub const RANDOM_SIGN_BITS: u32 = 4;

/// §4.4.4 ceiling on the periodic-case repeated pitch delay: `143`. The
/// delay is increased by one each subframe but "bounded by 143".
pub const PERIODIC_DELAY_CEIL: usize = 143;

/// §4.4 voicing class of a reconstructed 10 ms frame.
///
/// A frame is [`Periodic`](VoicingClass::Periodic) if at least one of its
/// two 5 ms subframes had a long-term prediction gain above 3 dB (the
/// eq (82) enable decision); otherwise it is
/// [`NonPeriodic`](VoicingClass::NonPeriodic). An erased frame inherits
/// the class of the previous reconstructed frame.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VoicingClass {
    /// At least one subframe was voiced (long-term prediction gain above
    /// 3 dB). The replacement excitation uses the adaptive codebook only
    /// (§4.4.4).
    Periodic,
    /// No subframe was voiced. The replacement excitation uses a random
    /// fixed-codebook contribution (§4.4.4).
    NonPeriodic,
}

/// One sample of the §4.4.4 non-periodic replacement excitation: the
/// random fixed-codebook **index** (13 bits) and **sign** field (4 bits)
/// drawn from successive eq (96) random numbers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RandomExcitation {
    /// The fixed-codebook index — the 13 LSBs of one random number
    /// (`0 ..= 8191`).
    pub index: u16,
    /// The fixed-codebook sign field — the 4 LSBs of the *next* random
    /// number (`0 ..= 15`).
    pub sign: u16,
}

/// §4.4 stateful frame-erasure concealer.
///
/// Owns the running voicing class (updated on every good frame, inherited
/// across erasures, spec §4.4), the eq (96) random seed, and the integer
/// pitch delay carried for the periodic-case eq-94 repeat. The
/// gain-attenuation equations (93)/(94)/(95) are pure functions and live
/// as associated functions; the decode chain owns the live gains and the
/// [`GainPredictor`] they attenuate.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Concealer {
    /// Voicing class of the most recent reconstructed frame. Start-up is
    /// [`VoicingClass::NonPeriodic`]: before any speech has been decoded
    /// there is no long-term structure to repeat, so an erasure on the
    /// very first frame falls back to the random (non-periodic) path.
    class: VoicingClass,
    /// eq (96) random-generator seed. Spec start-up `21845`
    /// ([`RANDOM_SEED_INIT`]).
    seed: u16,
    /// Integer pitch delay carried for the §4.4.4 periodic repeat — the
    /// integer part of the last good frame's pitch delay, then +1 per
    /// erased subframe (bounded [`PERIODIC_DELAY_CEIL`]).
    periodic_delay: usize,
}

impl Default for Concealer {
    fn default() -> Self {
        Self::new()
    }
}

impl Concealer {
    /// Builds a concealer in the start-up state: non-periodic class, the
    /// spec [`RANDOM_SEED_INIT`] seed, and a zero carried pitch delay.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            class: VoicingClass::NonPeriodic,
            seed: RANDOM_SEED_INIT,
            periodic_delay: 0,
        }
    }

    /// The current voicing class (the class of the last reconstructed
    /// frame; the class an immediate erasure would inherit).
    #[must_use]
    pub const fn class(&self) -> VoicingClass {
        self.class
    }

    /// The current eq (96) random seed (exposed for trace / test).
    #[must_use]
    pub const fn seed(&self) -> u16 {
        self.seed
    }

    /// The integer pitch delay currently carried for the §4.4.4 periodic
    /// repeat.
    #[must_use]
    pub const fn periodic_delay(&self) -> usize {
        self.periodic_delay
    }

    /// Update the running voicing class from a **good** frame's two
    /// subframe long-term-postfilter decisions (§4.4).
    ///
    /// The frame is [`Periodic`](VoicingClass::Periodic) iff at least one
    /// subframe was voiced — i.e. its
    /// [`LongTermDecision::gain`] is positive (the eq (82) enable test
    /// cleared the 0.5 threshold, the spec's "> 3 dB" long-term
    /// prediction gain). Also latches the integer part of the good
    /// frame's pitch delay so a subsequent erasure can repeat it
    /// (§4.4.4 periodic case).
    ///
    /// `subframes` is the per-subframe decision slice (length 2 for a
    /// G.729 frame, but any length is accepted); `int_pitch_delay` is the
    /// integer part of the frame's transmitted pitch delay.
    pub fn observe_good_frame(&mut self, subframes: &[LongTermDecision], int_pitch_delay: usize) {
        let voiced = subframes.iter().any(|d| d.gain > 0.0);
        self.class = if voiced {
            VoicingClass::Periodic
        } else {
            VoicingClass::NonPeriodic
        };
        // Latch the pitch delay the periodic repeat would start from,
        // bounded by the §4.4.4 ceiling.
        self.periodic_delay = int_pitch_delay.min(PERIODIC_DELAY_CEIL);
    }

    /// Is the *inherited* class [`Periodic`](VoicingClass::Periodic)?
    /// Used to pick the §4.4.4 excitation path for an erased frame.
    #[must_use]
    pub const fn is_periodic(&self) -> bool {
        matches!(self.class, VoicingClass::Periodic)
    }

    /// eq (93) fixed-codebook-gain attenuation (§4.4.2):
    /// `ĝ_c^(m) = 0.98 · ĝ_c^(m−1)`.
    #[must_use]
    pub fn attenuate_fixed_gain(prev_fixed_gain: f32) -> f32 {
        FIXED_GAIN_ATTENUATION * prev_fixed_gain
    }

    /// eq (94) adaptive-codebook-gain attenuation (§4.4.2):
    /// `ĝ_p^(m) = 0.9 · ĝ_p^(m−1)`, capped strictly below
    /// [`ADAPTIVE_GAIN_CAP`].
    ///
    /// The spec writes the bound as `ĝ_p^(m) < 0.9`; we realise the
    /// strict inequality by capping at one ULP below `0.9`
    /// ([`adaptive_gain_cap_below`]). For any physically meaningful
    /// previous gain (`ĝ_p^(m−1) ≤ 1`) the `0.9·` factor already lands
    /// below `0.9`, so the cap only fires defensively on an out-of-range
    /// input.
    #[must_use]
    pub fn attenuate_adaptive_gain(prev_adaptive_gain: f32) -> f32 {
        let attenuated = ADAPTIVE_GAIN_ATTENUATION * prev_adaptive_gain;
        attenuated.min(adaptive_gain_cap_below())
    }

    /// eq (95) gain-predictor-memory attenuation (§4.4.3): the value
    /// `Û^(m)` pushed onto an erased subframe's predictor memory is the
    /// 4-slot average of `Û^(m−i)` minus 4 dB, floored at
    /// [`PREDICTOR_MEMORY_FLOOR_DB`] (`−14`).
    ///
    /// Returns the scalar `Û^(m)` rather than mutating the predictor, so
    /// the decode chain can push it via
    /// [`GainPredictor`]'s history-advance helper exactly as it would a
    /// normal subframe value.
    #[must_use]
    pub fn attenuated_predictor_memory_db(predictor: &GainPredictor) -> f32 {
        let history = predictor.history_db();
        let sum: f32 = history.iter().take(MA_NP).sum();
        let averaged = PREDICTOR_MEMORY_AVERAGE_WEIGHT * sum;
        (averaged - PREDICTOR_MEMORY_ATTENUATION_DB).max(PREDICTOR_MEMORY_FLOOR_DB)
    }

    /// Advance the eq (96) random generator one step and return the new
    /// 16-bit value: `seed = 31821 · seed + 13849` (modulo `2^16`).
    fn next_random(&mut self) -> u16 {
        self.seed = self
            .seed
            .wrapping_mul(RANDOM_MULTIPLIER)
            .wrapping_add(RANDOM_INCREMENT);
        self.seed
    }

    /// §4.4.4 non-periodic replacement excitation for one subframe.
    ///
    /// Draws two successive eq (96) random numbers: the **index** from
    /// the 13 LSBs of the first, the **sign** field from the 4 LSBs of
    /// the second (clause 4.4.4). Advances the seed by two steps.
    pub fn next_random_excitation(&mut self) -> RandomExcitation {
        let index = self.next_random() & ((1 << RANDOM_INDEX_BITS) - 1);
        let sign = self.next_random() & ((1 << RANDOM_SIGN_BITS) - 1);
        RandomExcitation { index, sign }
    }

    /// §4.4.4 periodic-case pitch delay for the next erased subframe.
    ///
    /// "The pitch delay is based on the integer part of the pitch delay
    /// in the previous frame, and is repeated for each successive frame.
    /// To avoid excessive periodicity the delay is increased by one for
    /// each next subframe but bounded by 143." Returns the current
    /// carried delay and *then* advances it by one (bounded by
    /// [`PERIODIC_DELAY_CEIL`]) so the next call yields the incremented
    /// value.
    pub fn periodic_pitch_delay(&mut self) -> usize {
        let delay = self.periodic_delay.min(PERIODIC_DELAY_CEIL);
        self.periodic_delay = (delay + 1).min(PERIODIC_DELAY_CEIL);
        delay
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decision(gain: f32) -> LongTermDecision {
        LongTermDecision {
            delay: 40,
            frac: 0,
            gain,
        }
    }

    /// Start-up state: non-periodic class, spec seed 21845, zero carried
    /// delay.
    #[test]
    fn new_concealer_start_up_state() {
        let c = Concealer::new();
        assert_eq!(c.class(), VoicingClass::NonPeriodic);
        assert_eq!(c.seed(), 21845);
        assert_eq!(c.periodic_delay(), 0);
    }

    /// §4.4 spec constants are exactly the eq (93)–(96) values.
    #[test]
    fn spec_constants_match() {
        assert!((FIXED_GAIN_ATTENUATION - 0.98).abs() < 1e-9);
        assert!((ADAPTIVE_GAIN_ATTENUATION - 0.9).abs() < 1e-9);
        assert!((PREDICTOR_MEMORY_AVERAGE_WEIGHT - 0.25).abs() < 1e-9);
        assert!((PREDICTOR_MEMORY_ATTENUATION_DB - 4.0).abs() < 1e-9);
        assert!((PREDICTOR_MEMORY_FLOOR_DB - (-14.0)).abs() < 1e-9);
        assert_eq!(RANDOM_MULTIPLIER, 31821);
        assert_eq!(RANDOM_INCREMENT, 13849);
        assert_eq!(RANDOM_SEED_INIT, 21845);
        assert_eq!(RANDOM_INDEX_BITS, 13);
        assert_eq!(RANDOM_SIGN_BITS, 4);
        assert_eq!(PERIODIC_DELAY_CEIL, 143);
    }

    /// §4.4 classification: a frame with any voiced subframe is periodic.
    #[test]
    fn one_voiced_subframe_is_periodic() {
        let mut c = Concealer::new();
        c.observe_good_frame(&[decision(0.0), decision(0.7)], 60);
        assert_eq!(c.class(), VoicingClass::Periodic);
        assert!(c.is_periodic());
    }

    /// §4.4 classification: a frame with no voiced subframe is
    /// non-periodic.
    #[test]
    fn no_voiced_subframe_is_non_periodic() {
        let mut c = Concealer::new();
        c.observe_good_frame(&[decision(0.0), decision(0.0)], 60);
        assert_eq!(c.class(), VoicingClass::NonPeriodic);
        assert!(!c.is_periodic());
    }

    /// §4.4 "An erased frame inherits its class from the preceding
    /// frame": the class only changes on `observe_good_frame`, so an
    /// erasure (no observe call) keeps the latched class.
    #[test]
    fn erased_frame_inherits_class() {
        let mut c = Concealer::new();
        c.observe_good_frame(&[decision(0.5), decision(0.0)], 50);
        assert_eq!(c.class(), VoicingClass::Periodic);
        // Two erasures in a row: no observe, class stays periodic.
        assert!(c.is_periodic());
        assert!(c.is_periodic());
        // A good non-periodic frame flips it.
        c.observe_good_frame(&[decision(0.0), decision(0.0)], 50);
        assert_eq!(c.class(), VoicingClass::NonPeriodic);
    }

    /// eq (93): the fixed-codebook gain is attenuated by 0.98.
    #[test]
    fn eq93_fixed_gain_attenuation() {
        assert!((Concealer::attenuate_fixed_gain(1.0) - 0.98).abs() < 1e-6);
        assert!((Concealer::attenuate_fixed_gain(0.5) - 0.49).abs() < 1e-6);
        // Repeated erasures decay geometrically.
        let mut g = 1.0_f32;
        for _ in 0..3 {
            g = Concealer::attenuate_fixed_gain(g);
        }
        assert!((g - 0.98_f32.powi(3)).abs() < 1e-6);
    }

    /// eq (94): the adaptive gain is attenuated by 0.9, bounded < 0.9.
    #[test]
    fn eq94_adaptive_gain_attenuation_and_bound() {
        // Typical case: 0.9 * 0.8 = 0.72, well below the cap.
        assert!((Concealer::attenuate_adaptive_gain(0.8) - 0.72).abs() < 1e-6);
        // The result is always strictly below 0.9, even for an
        // out-of-range previous gain.
        let big = Concealer::attenuate_adaptive_gain(5.0);
        assert!(big < 0.9, "attenuated {big} must be < 0.9");
        // A unit previous gain attenuates to exactly 0.9 before the cap;
        // the cap pushes it strictly below.
        let unit = Concealer::attenuate_adaptive_gain(1.0);
        assert!(unit < 0.9, "0.9*1.0 capped to {unit} (< 0.9)");
        assert!((unit - 0.9).abs() < 1e-6);
    }

    /// eq (95): the predictor memory is the 4-slot average minus 4 dB,
    /// floored at -14. With the fresh predictor (all slots -14) the
    /// average is -14, minus 4 is -18, floored back to -14.
    #[test]
    fn eq95_predictor_memory_floored_at_minus14() {
        let p = GainPredictor::new();
        let u = Concealer::attenuated_predictor_memory_db(&p);
        assert!((u - (-14.0)).abs() < 1e-6, "Û = {u}");
    }

    /// eq (95): with a higher-energy predictor history the 4 dB
    /// attenuation is visible above the floor. Build a predictor whose
    /// four slots all read 0 dB (push γ̂ = 1 four times): average 0,
    /// minus 4 → -4 dB, which is above the -14 floor.
    #[test]
    fn eq95_predictor_memory_attenuates_by_4db_above_floor() {
        let mut p = GainPredictor::new();
        for _ in 0..MA_NP {
            p.push_quantised_error(1.0); // Û^(m) = 20*log10(1) = 0 dB
        }
        let u = Concealer::attenuated_predictor_memory_db(&p);
        assert!((u - (-4.0)).abs() < 1e-5, "Û = {u} expected -4 dB");
    }

    /// eq (96): the random generator matches `seed = 31821*seed + 13849`
    /// (mod 2^16) starting from the spec seed 21845.
    #[test]
    fn eq96_random_recurrence() {
        let mut c = Concealer::new();
        let expected1 = 21845_u16.wrapping_mul(31821).wrapping_add(13849);
        let r1 = c.next_random();
        assert_eq!(r1, expected1);
        let expected2 = expected1.wrapping_mul(31821).wrapping_add(13849);
        let r2 = c.next_random();
        assert_eq!(r2, expected2);
        // The seed tracks the last value.
        assert_eq!(c.seed(), expected2);
    }

    /// §4.4.4: the non-periodic excitation takes index from the 13 LSBs
    /// of one random number and sign from the 4 LSBs of the next, in
    /// that order, advancing the seed by two steps.
    #[test]
    fn random_excitation_index13_sign4_two_draws() {
        let mut c = Concealer::new();
        // Recompute the two raw draws independently.
        let raw1 = 21845_u16.wrapping_mul(31821).wrapping_add(13849);
        let raw2 = raw1.wrapping_mul(31821).wrapping_add(13849);
        let ex = c.next_random_excitation();
        assert_eq!(ex.index, raw1 & 0x1FFF);
        assert_eq!(ex.sign, raw2 & 0x0F);
        assert!(ex.index <= 0x1FFF);
        assert!(ex.sign <= 0x0F);
        // Seed advanced by exactly two steps.
        assert_eq!(c.seed(), raw2);
    }

    /// §4.4.4 periodic delay: starts at the latched integer pitch delay,
    /// increments by one per subframe, bounded by 143.
    #[test]
    fn periodic_delay_increments_and_bounds_at_143() {
        let mut c = Concealer::new();
        c.observe_good_frame(&[decision(0.6), decision(0.0)], 140);
        assert_eq!(c.periodic_pitch_delay(), 140);
        assert_eq!(c.periodic_pitch_delay(), 141);
        assert_eq!(c.periodic_pitch_delay(), 142);
        assert_eq!(c.periodic_pitch_delay(), 143);
        // Bounded at 143 — never exceeds.
        assert_eq!(c.periodic_pitch_delay(), 143);
        assert_eq!(c.periodic_pitch_delay(), 143);
    }

    /// §4.4.4 the latched periodic delay is itself clamped to 143 even
    /// if the observed good-frame delay exceeds it.
    #[test]
    fn observed_delay_clamped_to_ceiling() {
        let mut c = Concealer::new();
        c.observe_good_frame(&[decision(0.6), decision(0.0)], 200);
        assert_eq!(c.periodic_delay(), 143);
    }

    /// The random sequence is deterministic across two concealers driven
    /// in lockstep — all state is owned, no globals.
    #[test]
    fn deterministic_random_sequence() {
        let mut a = Concealer::new();
        let mut b = Concealer::new();
        for _ in 0..50 {
            assert_eq!(a.next_random_excitation(), b.next_random_excitation());
        }
    }

    /// The eq (96) generator visits many distinct values (it is not
    /// stuck): a 256-draw run produces a broad spread of indices.
    #[test]
    fn random_index_has_spread() {
        let mut c = Concealer::new();
        let mut seen = std::collections::HashSet::new();
        for _ in 0..256 {
            seen.insert(c.next_random_excitation().index);
        }
        // A linear congruential generator over 13-bit indices should
        // produce well over half distinct values in 256 draws.
        assert!(seen.len() > 128, "only {} distinct indices", seen.len());
    }
}
