//! # oxideav-g729
//!
//! **Status:** clean-room rebuild in progress.
//!
//! The prior implementation was retired under the workspace clean-room
//! policy: several source modules transcribed numeric tables verbatim
//! from an external reference-software distribution and described
//! matching its behaviour by citing specific source files of that
//! distribution. The clean-room policy forbids consulting any external
//! implementation's source for any reason, regardless of licensing.
//! The crate has been reset to a register-only scaffold (master
//! `676fc46`) and is being re-grown one spec-cited unit at a time.
//!
//! ## What is wired up
//!
//! Round 173 lands the bit-exact numeric-tables foundation:
//!
//! * §3.1 / §4.2 pre/post-processing IIR high-pass filter coefficients
//!   (100 Hz Q13 and 140 Hz Q12 variants).
//! * §4.1 spec Table 8 bit-allocation per analysis parameter.
//! * `basic_op()` Pow2, Log2, and Inv_sqrt 16-bit lookup tables.
//!
//! Round 191 adds a parser for the **ITU serial bitstream format**
//! used by the staged conformance corpus under
//! `docs/audio/g729/conformance/`. See [`serial`] for the 164-byte
//! frame layout (sync + bits-per-frame header + 80 bit-value words)
//! and [`serial::parse_frame`] for the decoder.
//!
//! See [`tables`] for the full inventory and Q-format conventions.
//!
//! ## What is NOT wired up
//!
//! Every decode/encode entry point still returns
//! [`Error::NotImplemented`]. The remaining codebook tables (gain
//! GA/GB, postfilter interpolation, taming, Annex B DTX/CNG, LSF↔LSP
//! cos/slope tables) are staged under `docs/audio/g729/tables/` but
//! not yet compiled in; the Implementer leaves them out until the
//! docs collaborator's specifier pass clarifies the per-clause
//! wire-up direction.
//!
//! ## Clean-room provenance
//!
//! All numeric tables under [`tables`] are generated by `build.rs`
//! from CSVs under `tables/<spec-name>.csv`, which are byte-for-byte
//! copies of the spec-role-named outputs under
//! `docs/audio/g729/tables/`. The extractor that produced those CSVs
//! reads only data-only `.c` table files staged alongside the spec;
//! per-file provenance (origin filename, byte ranges, file-level
//! SHA-256) is recorded in each CSV's `.meta` sidecar under
//! `docs/audio/g729/tables/`. No algorithmic source is consulted.

#![warn(missing_debug_implementations)]

use oxideav_core::RuntimeContext;

pub mod serial;
pub mod tables;

/// Crate-local error type. Until decode + encode are wired up, every
/// public codec entry point returns [`Error::NotImplemented`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    /// The crate has been reset to a scaffold pending clean-room
    /// rebuild; no decoder or encoder functionality is wired up yet.
    NotImplemented,
}

impl core::fmt::Display for Error {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "oxideav-g729: clean-room rebuild in progress — decoder/encoder not yet wired"
        )
    }
}

impl std::error::Error for Error {}

/// No-op codec registration — the rebuild scaffold registers nothing
/// runnable into the runtime context yet. The hook is preserved so
/// downstream consumers can keep their `register!` graphs intact.
pub fn register(_ctx: &mut RuntimeContext) {}

oxideav_core::register!("g729", register);
